# Site settings
title: eivindw writings
name: :kodemaker [:eivind]
km: http://www.kodemaker.no/eivind
description: eivindw writes about stuff he discovers at work, mostly JVM-related.
url: "http://eivindw.github.io"
twitter_username: eivindw
github_username: eivindw

# Build settings
markdown: kramdown
